name: TAG RC CREATOR
on:
  workflow_dispatch:
jobs:
  create_staging_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get Last Draft Release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GH_TOKEN }}
          draft: true
      - name: Calculate Tag RC
        run: |
          if [ -z "$(git tag)" ]; then
            git tag "${{ steps.last_release.outputs.tag_name }}-rc.1"
          else
            TAG_COUNT=$(git tag | grep "${{ steps.last_release.outputs.tag_name }}" | grep -P '^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$' | wc -l)
            NEW_RC_NUMBER=$((${TAG_COUNT} + 1))
            git tag "${{ steps.last_release.outputs.tag_name }}-rc.$NEW_RC_NUMBER"
          fi
      - name: Push Tag
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: "${{ secrets.GH_TOKEN }}"
          tags: true
          branch: "master"