name: DEPLOY (STAGING)
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
  workflow_dispatch:
  workflow_run:
    workflows: ["TAG RELEASE CANDIDATE"]
    types:
      - completed
jobs:
  deploy:
    name: deploy_stg
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Calculate artifact tag
        run: |
          if [[ ${{ github.event_name }} == workflow_dispatch ]]; then
            echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
          elif [[ ${{ github.event_name }} == push ]]; then
            tagvalue=$(echo ${{ github.ref }} | rev | cut -d'/' -f1 | rev)
            echo "TAG=$tagvalue" >> $GITHUB_ENV
          elif [[ ${{ github.event_name }} == workflow_run ]]; then
            tagvalue=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*-rc.[0-9]*' | sort -V | tail -n 1)
            echo "TAG=$tagvalue" >> $GITHUB_ENV
          fi
      - name: Print TAG
        run: |
          echo "The tag value is: $TAG"
