name: DEPLOY (STAGING)
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
  workflow_dispatch:
  workflow_run:
    workflows: ["TAG RELEASE CANDIDATE"]
    types:
      - completed
jobs:
  deploy:
    name: deploy_stg
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      # Build
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calculate artifact tag
        run: |
          if [ "${{ github.event_name }}" == workflow_dispatch ]; then
            echo "workflow_dispatch event detected!"
          elif [ "${{ github.event_name }}" == push ]; then
            echo "push event detected!"
          else [ "${{ github.event_name }}" == workflow_run ]; then
            echo "workflow_run event detected!"
          fi
