name: DEPLOY (STAGING)
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
  workflow_dispatch:
  workflow_run:
    workflows: ["TAG RELEASE CANDIDATE"]
    types:
      - completed
jobs:
  deploy:
    name: deploy_stg
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Calculate artifact tag (workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
      - name: Calculate artifact tag (push)
        if: ${{ github.event_name == 'push' }}
        run: |
          tagvalue=$(echo ${{ github.ref }} | rev | cut -d'/' -f1 | rev)
          echo "TAG=$tagvalue" >> $GITHUB_ENV
      - name: Calculate artifact tag (workflow_run)
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          tagvalue=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*-rc.[0-9]*' | sort -V | tail -n 1)
          echo "TAG=$tagvalue" >> $GITHUB_ENV
      - name: Print TAG
        run: |
          echo "The tag value is: $TAG"
